M48
; DRILL file {KiCad 7.0.10} date Mon Nov 11 15:26:42 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-11T15:26:42+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X184.05Y-74.31
X184.22Y-140.84
X250.8Y-74.3
X250.9Y-140.71
T2
X197.76Y-79.275
X197.76Y-134.885
M30
